export function generateEmailTemplate(startupName: string, report: string): string {
    // Convert markdown to HTML (basic conversion)
    const htmlContent = report
        .split('\n')
        .map(line => {
            // Headers
            if (line.startsWith('### ')) {
                return `<h3 style="color: #1e293b; font-size: 18px; font-weight: 600; margin: 24px 0 12px 0;">${line.substring(4)}</h3>`;
            }
            if (line.startsWith('## ')) {
                return `<h2 style="color: #0f172a; font-size: 22px; font-weight: 700; margin: 32px 0 16px 0;">${line.substring(3)}</h2>`;
            }
            if (line.startsWith('# ')) {
                return `<h1 style="color: #0f172a; font-size: 28px; font-weight: 800; margin: 40px 0 20px 0;">${line.substring(2)}</h1>`;
            }

            // Bold
            line = line.replace(/\*\*(.+?)\*\*/g, '<strong style="font-weight: 600; color: #0f172a;">$1</strong>');

            // Lists
            if (line.startsWith('- ')) {
                return `<li style="margin: 8px 0; color: #475569;">${line.substring(2)}</li>`;
            }

            // Regular paragraphs
            if (line.trim() && !line.startsWith('<')) {
                return `<p style="color: #475569; line-height: 1.7; margin: 12px 0;">${line}</p>`;
            }

            return line;
        })
        .join('\n');

    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Strategy Report: ${startupName}</title>
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f8fafc;">
    <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #f8fafc; padding: 40px 20px;">
        <tr>
            <td align="center">
                <table width="600" cellpadding="0" cellspacing="0" style="background-color: #ffffff; border-radius: 12px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); overflow: hidden;">
                    <!-- Header -->
                    <tr>
                        <td style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px 40px 32px 40px; text-align: center;">
                            <h1 style="margin: 0; color: #ffffff; font-size: 28px; font-weight: 800;">
                                📊 Product Strategy Report
                            </h1>
                            <p style="margin: 12px 0 0 0; color: #e0e7ff; font-size: 18px; font-weight: 500;">
                                ${startupName}
                            </p>
                        </td>
                    </tr>
                    
                    <!-- Content -->
                    <tr>
                        <td style="padding: 40px;">
                            <p style="color: #64748b; font-size: 14px; margin: 0 0 24px 0; border-left: 4px solid #667eea; padding-left: 16px;">
                                This report was generated by the <strong>SaaS Viability Analyzer</strong> AI system.
                            </p>
                            
                            ${htmlContent}
                        </td>
                    </tr>
                    
                    <!-- Footer -->
                    <tr>
                        <td style="background-color: #f1f5f9; padding: 32px 40px; border-top: 1px solid #e2e8f0;">
                            <p style="margin: 0 0 8px 0; color: #64748b; font-size: 14px; text-align: center;">
                                Generated by <strong style="color: #475569;">SaaS Viability Analyzer</strong>
                            </p>
                            <p style="margin: 0; color: #94a3b8; font-size: 12px; text-align: center;">
                                AI-powered analysis for startup replication opportunities
                            </p>
                        </td>
                    </tr>
                </table>
                
                <!-- Disclaimer -->
                <p style="margin: 24px 0 0 0; color: #94a3b8; font-size: 12px; text-align: center; max-width: 600px;">
                    This analysis is AI-generated and should be used as a starting point for further research.
                    Always conduct your own due diligence before making business decisions.
                </p>
            </td>
        </tr>
    </table>
</body>
</html>
    `.trim();
}
